//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.NewDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLicense
    {
        public short LicenseID { get; set; }
        public string LicenseName { get; set; }
        public Nullable<short> NoOfUsers { get; set; }
        public Nullable<short> NoOfDevices { get; set; }
        public Nullable<short> NoOfEmp { get; set; }
    }
}
