//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.NewDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventImage
    {
        public int TranNo { get; set; }
        public Nullable<int> FKPollData { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> EvDate { get; set; }
        public string EvTime { get; set; }
        public Nullable<int> FpID { get; set; }
        public Nullable<short> RdrID { get; set; }
    }
}
