//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.NewDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvAppl
    {
        public int LvID { get; set; }
        public Nullable<System.DateTime> LvDate { get; set; }
        public string LvType { get; set; }
        public string EmpNo { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<float> NoDays { get; set; }
        public Nullable<byte> HalfLeave { get; set; }
        public Nullable<byte> HalfAbsent { get; set; }
        public string LvReason { get; set; }
        public string LvAddress { get; set; }
        public string DReason { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public string Status { get; set; }
    }
}
