//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.NewDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollDataLive
    {
        public int TranNo { get; set; }
        public Nullable<int> FpID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryTime { get; set; }
        public Nullable<short> ReaderID { get; set; }
        public Nullable<int> EntryCode { get; set; }
        public string EmpDate { get; set; }
    }
}
