//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.NewDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisData
    {
        public int VDataID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public string VisName { get; set; }
        public string Purpose { get; set; }
        public string EmpID { get; set; }
        public Nullable<short> VLevelID { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> ArrDate { get; set; }
        public string ArrTime { get; set; }
        public Nullable<System.DateTime> DepDate { get; set; }
        public string DepTime { get; set; }
        public string PickupCity { get; set; }
        public string DropCity { get; set; }
        public string Remarks { get; set; }
        public string VisitType { get; set; }
        public string Status { get; set; }
        public string Accomd { get; set; }
        public Nullable<byte> SafetyInd { get; set; }
    }
}
