//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.NewDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int VisID { get; set; }
        public string VisName { get; set; }
        public string NicNo { get; set; }
        public string Address1 { get; set; }
        public string Company { get; set; }
        public string OffPhone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> VisType { get; set; }
    }
}
