//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int UserAccessID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserAccessRoleID { get; set; }
        public Nullable<int> CriteriaData { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserAccess UserAccess1 { get; set; }
        public virtual UserAccess UserAccess2 { get; set; }
        public virtual UserAccessRole UserAccessRole { get; set; }
    }
}
