//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessRole
    {
        public UserAccessRole()
        {
            this.UserAccesses = new HashSet<UserAccess>();
            this.UserAccesses1 = new HashSet<UserAccess>();
        }
    
        public int UserDataAccessID { get; set; }
        public string DataAccessRole { get; set; }
        public string DataAccessLegend { get; set; }
        public int DataAccessType { get; set; }
    
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
        public virtual ICollection<UserAccess> UserAccesses1 { get; set; }
    }
}
